version: '3.8'

services:
  nextjs:
    image: node:18
    container_name: rez-application
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      -  '3001:3000'
    env_file:
      - .env.local
    restart: always
    command: sh -c "npm install && npm run build && npm start"

  # Cron service for automated payment deadline checks
  payment-checker:
    image: curlimages/curl:latest
    container_name: rez-payment-checker
    depends_on:
      - nextjs
    environment:
      - API_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}/api/check-payment-deadlines
      - PAYMENT_CHECK_TOKEN=${PAYMENT_CHECK_TOKEN:-default-secure-token}
    restart: always
    command: >
      sh -c "
        echo '* * * * * curl -X POST -H \"Authorization: Bearer $${PAYMENT_CHECK_TOKEN}\" -H \"Content-Type: application/json\" $${API_URL} >> /var/log/payment-check.log 2>&1' > /etc/crontabs/root &&
        crond -f
      "